# Generated by Django 3.2.6 on 2022-12-22 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, verbose_name='Theme')),
                ('sub_theme', models.CharField(max_length=50, verbose_name='Subtheme')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('heading', models.CharField(max_length=50, verbose_name='Heading')),
                ('main_text', models.TextField(max_length=10000, verbose_name='Main text')),
            ],
        ),
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('themes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.themes')),
            ],
            options={
                'verbose_name': 'Architecture',
                'verbose_name_plural': 'Architecture',
            },
            bases=('main.themes',),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('themes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.themes')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Music',
            },
            bases=('main.themes',),
        ),
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('themes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.themes')),
            ],
            options={
                'verbose_name': 'Politics',
                'verbose_name_plural': 'Politics',
            },
            bases=('main.themes',),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('themes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.themes')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sport',
            },
            bases=('main.themes',),
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('themes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.themes')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technology',
            },
            bases=('main.themes',),
        ),
    ]
